# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 4
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker
      stages:
        - name: go deps
          script: go mod tidy

v1.0.*:
  tag_push:
    - docker:
        build: .ide/Dockerfile
      stages:
        - name: changelog
          image: cnbcool/changelog
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: create release
          type: git:release
          options:
            title: release
            description: ${LATEST_CHANGE_LOG}
        - name: build
          script:
            - chmod +x build.sh
            - ./build.sh
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - build/*.exe
              - build/mcp-alapi-cn-*-linux-*
              - build/mcp-alapi-cn-*-darwin-*